services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    depends_on:
      - auth-service
      - acad-service
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-network

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    cpus: 0.5
    mem_limit: 512m
    depends_on:
      - auth-db
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=mongodb://auth-db:27017/auth
      - JWT_SECRET=Vzl2rkSw4GNdn+3gH6Q5BleIkTs9FOa5wI6qiPFp3lHCSm8iX0nc9uEkZ0+yExnC
    ports:
      - "3001:3001"
    networks:
      - microservices-network
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  # Auth Database
  auth-db:
    image: mongo:6.0
    container_name: auth-db
    restart: always
    networks:
      - microservices-network
    volumes:
      - auth-data:/data/db
    ports:
      - "27017:27017"

  acad-service:
    build: ./acad-service
    container_name: acad-service
    depends_on:
      - acad-db
    environment:
      - DB_HOST=acad-db
      - DB_PORT=5432
      - DB_NAME=db_kelas
      - DB_USER=ibnuzhrnllll
      - DB_PASSWORD=duniagamesss
    ports:
      - "3002:3002"
    networks:
      - microservices-network
    volumes:
      - ./acad-service:/app

  acad-db:
    image: postgres:16
    container_name: acad-db
    environment:
      - POSTGRES_USER=ibnuzhrnllll
      - POSTGRES_PASSWORD=duniagamesss
      - POSTGRES_DB=db_kelas
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    volumes:
      - ./acad-service/data/db_kelas.sql:/docker-entrypoint-initdb.d

networks:
  microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/28

volumes:
  auth-data:
  product-data:
  order-data: